---

- name: Ensure unattended-upgrades is installed
  apt:
    name: unattended-upgrades
    state: present
    update_cache: yes

- name: Apply unattended-upgrades configuration
  template:
    src: 51myunattended-upgrades.js2
    dest: /etc/apt/apt.conf.d/51myunattended-upgrades
    owner: root
    group: root
    mode: '0644'

- name: Restart unattended-upgrades service to apply changes
  systemd:
    name: unattended-upgrades
    state: restarted
